tasks:
    - init: |
        npm install
        docker compose build
      command: docker compose up

ports:
    - port: 3000
      visibility: public
      onOpen: open-preview

vscode:
    extensions:
        - esbenp.prettier-vscode

# TODO: show prebuild (runs init tasks on each master commit)
github:
    prebuilds:
        master: true
