apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-db"
  labels:
    katenary.io/component: db
    katenary.io/project: "{{ .Chart.Name }}"
    katenary.io/release: "{{ .Release.Name }}"
  annotations:
    katenary.io/docker-compose-sha1: f1921ecb95b0f8b2e691d83edf4f3d2bd8552631
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: db
      katenary.io/release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        katenary.io/component: db
        katenary.io/release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: db
          image: '{{ .Values.db.repository.image }}{{ if ne .Values.db.repository.tag "" }}:{{ .Values.db.repository.tag }}{{ end }}'
          ports:
            - name: db
            containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
            value: "{{ tpl .Values.db.environment.POSTGRES_PASSWORD . }}"
            - name: POSTGRES_DB
            value: "{{ tpl .Values.db.environment.POSTGRES_DB . }}"
          volumeMounts:
            - name: initdb
            mountPath: "/docker-entrypoint-initdb.d"
            readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: initdb
