apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ .Release.Name }}-urlshortener"
    labels:
    katenary.io/component: urlshortener
    katenary.io/project: "{{ .Chart.Name }}"
    katenary.io/release: "{{ .Release.Name }}"
    annotations:
    katenary.io/docker-compose-sha1: f1921ecb95b0f8b2e691d83edf4f3d2bd8552631
    katenary.io/version: 2.0.0-beta2
spec:
    replicas: 1
    selector:
    matchLabels:
        katenary.io/component: urlshortener
        katenary.io/release: "{{ .Release.Name }}"
    template:
    metadata:
        labels:
        katenary.io/component: urlshortener
        katenary.io/release: "{{ .Release.Name }}"
    spec:
        initContainers:
            - name: check-db
              image: busybox
              command:
                  - sh
                  - -c
                  - |-
                      OK=0
                      echo "Checking db port"
                      while [ $OK != 1 ]; do
                        echo -n "."
                        nc -z {{ .Release.Name }}-db 5432 2>&1 >/dev/null && OK=1 || sleep 1
                      done
                      echo
                      echo "Done"
        containers:
            - name: urlshortener
              image: '{{ .Values.urlshortener.repository.image }}{{ if ne .Values.urlshortener.repository.tag "" }}:{{ .Values.urlshortener.repository.tag }}{{ end }}'
              ports:
                  - name: urlshortener
                    containerPort: 3000
              env:
                  - name: PGPASSWORD
                    value: "{{ tpl .Values.urlshortener.environment.PGPASSWORD . }}"
                  - name: PGDATABASE
                    value: "{{ tpl .Values.urlshortener.environment.PGDATABASE . }}"
                  - name: PGHOST
                    value: "{{ tpl .Values.urlshortener.environment.PGHOST . }}"
                  - name: PGPORT
                    value: "{{ tpl .Values.urlshortener.environment.PGPORT . }}"
                  - name: PGUSER
                    value: "{{ tpl .Values.urlshortener.environment.PGUSER . }}"
